[package]
name = "fusion_plus"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
fusion_plus = "0x160df7d8e10750b56b86779cc8f400ad4145fad6cfd1a16dfb532c07302bcf8b"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }

[dev-dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }

[profile.default]
# Enable all linters
all_features = true
# Enable all warnings
warnings = true
# Enable all checks
check = true
# Enable all tests
test = true
# Enable all documentation
doc = true
# Enable all formatting
fmt = true
# Enable all verification
verify = true

[profile.release]
# Optimize for size
optimize = true
# Enable all linters
all_features = true
# Enable all warnings
warnings = true
# Enable all checks
check = true
# Enable all tests
test = true
# Enable all documentation
doc = true
# Enable all formatting
fmt = true
# Enable all verification
verify = true

[profile.test]
# Enable all linters
all_features = true
# Enable all warnings
warnings = true
# Enable all checks
check = true
# Enable all tests
test = true
# Enable all documentation
doc = true
# Enable all formatting
fmt = true
# Enable all verification
verify = true