[package]
name = "fusion_plus"
version = "1.0.0"
upgrade_policy = "compatible"

[addresses]
fusion_plus = "0x5f28002a709921a3bad09df582cdd99a7cab3ec300e99c88fbf50a354e62973b"


[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "movement" }

[dev-dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "movement" }

[profile.default]
# Enable all linters
all_features = true
# Enable all warnings
warnings = true
# Enable all checks
check = true
# Enable all tests
test = true
# Enable all documentation
doc = true
# Enable all formatting
fmt = true
# Enable all verification
verify = true

[profile.release]
# Optimize for size
optimize = true
# Enable all linters
all_features = true
# Enable all warnings
warnings = true
# Enable all checks
check = true
# Enable all tests
test = true
# Enable all documentation
doc = true
# Enable all formatting
fmt = true
# Enable all verification
verify = true

[profile.test]
# Enable all linters
all_features = true
# Enable all warnings
warnings = true
# Enable all checks
check = true
# Enable all tests
test = true
# Enable all documentation
doc = true
# Enable all formatting
fmt = true
# Enable all verification
verify = true